# default options - https://bind9.readthedocs.io/en/latest/chapter3.html
options {
  version "9";
  listen-on { any; };
  listen-on-v6 { any; };
  zone-statistics yes;
  max-cache-size 60m;
  interface-interval 60;
  max-ncache-ttl 10800;
  max-udp-size 4096;
  forwarders { 1.1.1.1; 8.8.8.8; 8.8.4.4; };
  notify yes;
  allow-transfer { trusted; };
  transfer-format many-answers;
  allow-query { any; };
  allow-recursion { any; };
  allow-query-cache { any; };
  auth-nxdomain no;
  dnssec-validation auto;
  directory "/var/bind";
  managed-keys-directory "/etc/bind/keys";
  pid-file "/run/named/named.pid";
  dump-file "/var/log/named/dump.db";
  statistics-file "/var/log/named/named.stats";
  memstatistics-file "/var/log/named/mem.stats";
};
#####################################################################
# access settings
acl "all" { 0.0.0.0/0; ::/0; };
acl "trusted" { 10.0.0.0/8; 127.0.0.0/8; 172.16.0.0/12; 192.168.0.0/16; };
#####################################################################
# rndc keys
key "certbot." { algorithm hmac-sha256; secret "REPLACE_KEY_CERTBOT"; };
key "rndc-key" { algorithm hmac-sha256; secret "REPLACE_KEY_RNDC"; };
key "dhcp-key" { algorithm hmac-sha256; secret "REPLACE_KEY_DHCP"; };
key "backup-key" { algorithm hmac-sha256; secret "REPLACE_KEY_BACKUP"; };
#####################################################################
# rndc settings
controls { inet 127.0.0.1 allow { trusted; } keys { "rndc-key"; }; };
#####################################################################
# named logging options
logging {
channel querylog      { file "/var/log/entrypoint.log"; severity info; print-category no; print-severity no; print-time yes; };
channel update        { file "/var/log/entrypoint.log"; severity info; print-category no; print-severity no; print-time yes; };
channel xfer-in       { file "/var/log/entrypoint.log"; severity info; print-category no; print-severity no; print-time yes; };
channel xfer-out      { file "/var/log/entrypoint.log"; severity info; print-category no; print-severity no; print-time yes; };
channel security      { file "/var/log/named/security.log"; severity dynamic; print-severity yes; print-time yes; };
channel notify        { file "/var/log/named/notify.log"; severity info; print-category no; print-severity no; print-time yes; };
channel debug         { file "/var/log/named/debug.log"; severity debug; print-category yes; print-severity yes; print-time yes; };
channel database      { file "/var/log/named/database.log"; severity info; print-category no; print-severity no; print-time yes; };
channel resolver      { file "/var/log/named/resolver.log"; severity info; print-category no; print-severity no; print-time yes; };
channel default       { file "/var/log/named/default.log"; severity debug; print-category yes; print-severity yes; print-time yes; };
category default      { default; debug; };
category dispatch     { default; };
category queries      { querylog; };
category update       { update; };
category network      { default; };
category unmatched    { default; };
category client       { default; };
category notify       { notify; };
category config       { default; };
category security     { security; };
category database     { database; };
category general      { default; };
category dnssec       { security; };
category xfer-in      { xfer-in; default; };
category xfer-out     { xfer-out; default; };
category resolver     { resolver; default; };
category lame-servers { default; };
};

#  ********** begin root info **********
zone "." {
    type hint;
    file "/var/bind/root.cache";
};
#  ********** end root info **********
# end
#####################################################################
