# Default nginx configuration
user                                         REPLACE_SERVICE_USER;
worker_processes                             2;
daemon                                       off;
error_log                                    /data/log/nginx/nginx.log warn;
pid                                          /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    sendfile                                 on;
    keepalive_timeout                        65;
    gzip                                     on;
    default_type                             "text/html";
    include                                  /etc/nginx/mime.types;
    access_log                               /data/log/nginx/nginx.access.log;
    map                                      $http_upgrade $connection_upgrade { default upgrade; '' close; }

    server {
        listen                               SERVER_PORT;
        root                                 /data/htdocs/www;
        index                                index.html index.php index.cgi index.pl index.aspx awstats.pl index.unknown.php index.default.php index.txt index.json;
        proxy_intercept_errors               off;
        add_header X-Frame-Options           "SAMEORIGIN" always;
        add_header X-XSS-Protection          "1; mode=block" always;
        add_header X-Content-Type-Options    "nosniff" always;
        add_header Referrer-Policy           "no-referrer-when-downgrade" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header Content-Security-Policy   "script-src 'self' 'unsafe-inline' 'unsafe-eval' *; frame-src 'self' *; object-src 'self'" always;

        location = /favicon.ico {
            log_not_found                    off;
            access_log                       off;
        }

        location = /robots.txt {
            allow                            all;
            log_not_found                    off;
            access_log                       off;
        }

        location /health {
            default_type text/html;
            allow                            all;
            access_log                       off;
            return                           200 'OK';
        }

        location /health/json {
            default_type application/json;
            allow                            all;
            access_log                       off;
            return                           200 '{"status":"OK"}';
        }
        
        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            if (!-f $document_root$fastcgi_script_name) {
                return 404;
            }
            fastcgi_param                    HTTP_PROXY "";
            fastcgi_pass                     127.0.0.1:9000;
            fastcgi_index                    index.php;
            include                          fastcgi_params;
            fastcgi_param                    SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location /nginx_status {
            stub_status;
        }
    }
}
